baseURL = 'https://aurora.github.io/ECS_Advanced_Networking_Workshop/'
languageCode = 'vi-vn'
title = 'Workshop ECS Advanced Networking'
theme = 'hugo-theme-learn'
defaultContentLanguage = 'vi'

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = "https://github.com/aurora/ECS_Advanced_Networking_Workshop/edit/main/content"
  description = "Workshop thực hành ECS Advanced Networking - Service Discovery, Load Balancing và Security trên AWS"
  author = "AWS Workshop Team"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableSearch = false
  disableShortcutsTitle = false
  disableLanguageSwitchingButton = true
  highlightClientSide = true
  menushortcutsnewtab = true

# Menu shortcuts
[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Repository"
identifier = "GitHub Repo"
url = "https://github.com/aurora/ECS_Advanced_Networking_Workshop"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-cloud'></i> AWS Console"
identifier = "AWS Console"
url = "https://console.aws.amazon.com/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i> AWS Documentation"
identifier = "AWS Docs"
url = "https://docs.aws.amazon.com/ecs/"
weight = 30

# Markup configuration
[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"
    
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Search configuration
[params.search]
  client = "fuse"
  fusejsconfig = """
{
  "ignoreLocation": true,
  "threshold": 0.1,
  "location": 0,
  "distance": 100,
  "maxPatternLength": 32,
  "minMatchCharLength": 1,
  "keys": [
    "title",
    "tags",
    "content"
  ]
}
"""
