baseURL = 'https://binh2423.github.io/ECS_Advanced_Networking/'
languageCode = 'vi-vn'
title = 'ECS_Advanced_Networking_Workshop'
theme = 'hugo-theme-learn'
defaultContentLanguage = 'vi'
relativeURLs = false
canonifyURLs = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = "https://github.com/Binh2423/ECS_Advanced_Networking/edit/main/content"
  description = "Workshop thực hành ECS Advanced Networking - Service Discovery, Load Balancing và Security trên AWS"
  author = "ECS_Advanced_Networking_Workshop"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableSearch = false
  disableShortcutsTitle = false
  disableLanguageSwitchingButton = true
  highlightClientSide = true
  menushortcutsnewtab = true
  
  # Image optimization
  [params.imageProcessing]
    anchor = "smart"
    bgColor = "#ffffff"
    hint = "photo"
    quality = 85
    resampleFilter = "box"

# Menu shortcuts
[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Repository"
identifier = "GitHub Repo"
url = "https://github.com/Binh2423/ECS_Advanced_Networking"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-cloud'></i> AWS Console"
identifier = "AWS Console"
url = "https://console.aws.amazon.com/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i> AWS Documentation"
identifier = "AWS Docs"
url = "https://docs.aws.amazon.com/ecs/"
weight = 30

# Markup configuration
[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"
    
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      linkify = true
      strikethrough = true
      table = true
      taskList = true

# Search configuration
[params.search]
  client = "fuse"
  fusejsconfig = """
{
  "ignoreLocation": true,
  "threshold": 0.1,
  "location": 0,
  "distance": 100,
  "maxPatternLength": 32,
  "minMatchCharLength": 1,
  "keys": [
    "title",
    "tags",
    "content"
  ]
}
"""
